// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJK6jNiCBLoCnJfJWHMv9XY-fmwKC4u24',
    appId: '1:104336687114:web:b0d595ca6f496e6cf05ff3',
    messagingSenderId: '104336687114',
    projectId: 'e-commerce-app-95893',
    authDomain: 'e-commerce-app-95893.firebaseapp.com',
    storageBucket: 'e-commerce-app-95893.appspot.com',
    measurementId: 'G-4KH7TEBHMR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQmQWhrmIsuOFKHudHCGVlNBOBinjAwlw',
    appId: '1:104336687114:android:dabd1d70b2be3351f05ff3',
    messagingSenderId: '104336687114',
    projectId: 'e-commerce-app-95893',
    storageBucket: 'e-commerce-app-95893.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCguP1RwIFLFuAreGfkDLYpdcn03AGNwxM',
    appId: '1:104336687114:ios:87188bf8ba13c396f05ff3',
    messagingSenderId: '104336687114',
    projectId: 'e-commerce-app-95893',
    storageBucket: 'e-commerce-app-95893.appspot.com',
    iosClientId: '104336687114-rd5bdvhl0k24ggk6dl0v1ta6213kv2vh.apps.googleusercontent.com',
    iosBundleId: 'com.example.example',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCguP1RwIFLFuAreGfkDLYpdcn03AGNwxM',
    appId: '1:104336687114:ios:87188bf8ba13c396f05ff3',
    messagingSenderId: '104336687114',
    projectId: 'e-commerce-app-95893',
    storageBucket: 'e-commerce-app-95893.appspot.com',
    iosClientId: '104336687114-rd5bdvhl0k24ggk6dl0v1ta6213kv2vh.apps.googleusercontent.com',
    iosBundleId: 'com.example.example',
  );
}
